### ISSUE TITLE
Intellij 2021.1 can't start up

### ISSUE THREAD

**Issue by strange-qwq** [codota/codota-plugin-intellij#8]
log:

java.util.concurrent.CompletionException: org.picocontainer.PicoRegistrationException: Key com.codota.intellij.common.utils.StatsCollectorBridge duplicated
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
    at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt:387)
    at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
    at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
    at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
    at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:384)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.a.a(a.java:110)
    at com.intellij.ide.b.a.aw.a(aw.java:109)
    at com.intellij.ide.b.a.Y.b(Y.java:275)
    at com.intellij.ide.b.a.Y.a(Y.java:133)
    at com.intellij.ide.b.l.c.a(c.java:93)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.idea.MainImpl.start(MainImpl.java:102)
    at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:305)
    at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:245)
    at com.intellij.ide.plugins.MainRunner.lambda$start$1(MainRunner.java:41)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.picocontainer.PicoRegistrationException: Key com.codota.intellij.common.utils.StatsCollectorBridge duplicated
    at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:119)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:400)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:250)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:106)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
    ... 27 more

-----
Your JRE: 11.0.9.1+11-b1257.1 amd64 (JetBrains s.r.o.)
C:\Program Files\JetBrains\IntelliJ IDEA 211.4961.30\jbr

**Comment by StefanLobbenmeier** [comment]
To repair this I deleted the "completion" folders from 
`C:\Program Files\JetBrains\IntelliJ IDEA 211.5538.20\plugins`

- completionMlRanking
- completionMlRankingModels
